# Generated by Django 4.2.2 on 2023-07-13 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
