# Generated by Django 4.2.2 on 2023-08-08 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("otp_totp", "0002_auto_20190420_0723"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomTOTPDevice",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("otp_totp.totpdevice",),
        ),
    ]
