# Generated by Django 4.2.2 on 2023-07-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("public_key", models.CharField(max_length=250)),
                ("secret_key", models.CharField(max_length=250)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
