# Generated by Django 4.2.2 on 2023-08-08 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("otp_hotp", "0002_auto_20190420_0723"),
        ("user", "0002_customtotpdevice"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomHOTPDevice",
            fields=[],
            options={
                "abstract": False,
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("otp_hotp.hotpdevice",),
        ),
    ]
