# Generated by Django 4.2.2 on 2023-07-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_siteowner_public_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteowner",
            name="iv",
            field=models.BinaryField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="siteowner",
            name="public_key",
            field=models.BinaryField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="siteowner",
            name="secret_key",
            field=models.BinaryField(blank=True, max_length=250, null=True),
        ),
    ]
