# Generated by Django 4.2.2 on 2023-07-21 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("user", "0006_siteowner_iv_alter_siteowner_public_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteowner",
            name="iv",
        ),
        migrations.AddField(
            model_name="siteowner",
            name="site",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_site",
                to="sites.site",
            ),
            preserve_default=False,
        ),
    ]
